[settings]

; Detailed documentation of the settings is available in the 'settings.md' file (for basic settings) and 'advanced.md' (for advanced settings).
; To use optional parameters, such as 'head' or 'compare', uncomment them by deleting the semi-colon in the beginning of the line.  

; ************** BASIC SETTINGS (see settings.md) **************
;___GENERAL SETTINGS___
input = sample/input/es_gsd-merged.conllu
output = sample/output_svo/ES_GSD.tsv

;___TREE SPECIFICATIONS___
;node_type = form
labeled = yes
label_subtypes = no
fixed = yes

;___TREE RESTRICTIONS___
size = 1-5
;head = upos=VERB
;ignored_labels = punct|reparandum|discourse
;allowed_labels = nsubj|obj

; ___SEARCH BY QUERY___
;query = upos=VERB >obj _
query = upos=VERB >nsubj _ >obj _

;___ADDITIONAL STATISTICS___
association_measures = no
;compare = ..\..\1_corpora\English\GUM - split - final\written-GUM_2.15.conllu

;___VISUALISATION___
example = yes
grew_match = yes
depsearch = no
node_info = no

;___OUTPUT THRESHOLD___
;frequency_threshold = 2
;max_lines = 100


; ************** ADVANCED SETTINGS (see advanced.md) **************
internal_saves = ./internal_saves
cpu_cores = 2
;continuation_processing = no
greedy_counter = yes
complete = no
processing_size = 1-5
;sentence_count_file = number_of_matched_trees_per_sentence.txt
;detailed_results_file = list_of_all_sentences_with_matched_trees.txt

